import { BenefitState, BenefitHistoryItem, BookItem, OrderItem, RefundHistoryItem } from './types';

export const initialBenefitState: BenefitState = {
  user: {
    name: '김민서',
    grade: '일반',
    employeeId: 'YP-20240912',
    isVerified: true,
    email: 'junkyo.jung@ypbooks.co.kr',
    phone: '010-1234-5678',
    birthDate: '1990-05-15',
    gender: 'male',
    address: '서울특별시 강남구 강남대로 408',
    detailAddress: 'YBM빌딩 지하 1층 영풍문고 강남점 (배송 요청사항: 부재 시 문 앞)',
  },
  semester: '2026년도 상반기',
  expiryDate: '2026.06.30',
  personalBook: {
    totalLimit: 10000,
    usedAmount: 5000,
    remainingAmount: 5000,
    rate: 50,
  },
  recommendedBook: {
    totalLimitCount: 1,
    usedCount: 1,
    recentBookTitle: '『AI 시대의 일하는 방식』 (18,000원 전액)',
    recentAmount: 18000,
  },
};

export const benefitHistories: BenefitHistoryItem[] = [
  {
    id: 'bh-1',
    date: '2026.09.10',
    type: '추천도서',
    bookTitle: '『AI 시대의 일하는 방식』',
    originalPrice: 18000,
    policy: '100% 전액지원',
    benefitAmount: -18000,
    selfPayAmount: 0,
    orderNumber: 'YP20260910-0842',
    status: '배송완료',
  },
  {
    id: 'bh-2',
    date: '2026.09.04',
    type: '개인도서',
    bookTitle: '『트렌드 코리아 2026』',
    originalPrice: 10000,
    policy: '50% 지원',
    benefitAmount: -5000,
    selfPayAmount: 5000,
    orderNumber: 'YP20260904-0193',
    status: '배송완료',
  },
];

export const initialWishlistBooks: BookItem[] = [
  {
    id: 'b-1',
    title: '『AI 시대의 일하는 방식』',
    subTitle: 'AI 협업과 생산성 혁신 가이드',
    author: '김영훈',
    publisher: '위즈덤하우스',
    originalPrice: 18000,
    salePrice: 16200,
    discountRate: 10,
    pointReward: 900,
    category: '추천도서',
    coverColor: '#1E3A8A', // Deep Navy
    coverLabel: 'AI 시대의\n일하는 방식',
    supportType: 'recommended',
    supportBadge: '100% 임직원 전액지원 대상',
    shippingInfo: '내일(화) 도착 예정',
    estimatedSelfPay: 0,
    benefitDiscount: 16200,
    wishDate: '2026.09.14',
    selected: true,
    likesCount: 2431,
  },
  {
    id: 'b-2',
    title: '『트렌드 코리아 2026』',
    subTitle: '2026 대한민국 소비트렌드 전망',
    author: '김난도, 전미영, 최지혜 외',
    publisher: '미래의창',
    originalPrice: 20000,
    salePrice: 18000,
    discountRate: 10,
    pointReward: 1000,
    category: '개인도서',
    coverColor: '#DC2626', // Bright Crimson
    coverLabel: '트렌드\n코리아\n2026',
    supportType: 'personal',
    supportBadge: '개인도서 지원금 5,000원 적용 가능',
    shippingInfo: '내일(화) 도착 예정',
    estimatedSelfPay: 13000,
    benefitDiscount: 5000,
    wishDate: '2026.09.13',
    selected: true,
    likesCount: 5812,
  },
  {
    id: 'b-3',
    title: '『불편한 편의점』 (벚꽃 에디션)',
    subTitle: '웃음과 감동의 온기 가득한 골목 편의점 이야기',
    author: '김호연',
    publisher: '나무옆의자',
    originalPrice: 14000,
    salePrice: 12600,
    discountRate: 10,
    pointReward: 700,
    category: '소설',
    coverColor: '#059669', // Emerald Green
    coverLabel: '불편한\n편의점',
    supportType: 'general',
    supportBadge: '스테디셀러 소득공제 대상',
    shippingInfo: '당일출고 가능 (15시 전 주문)',
    estimatedSelfPay: 12600,
    benefitDiscount: 0,
    wishDate: '2026.09.10',
    selected: true,
    likesCount: 12490,
  },
  {
    id: 'b-4',
    title: '『모던 자바스크립트 Deep Dive』',
    subTitle: '자바스크립트의 기본 개념과 동작 원리',
    author: '이웅모',
    publisher: '위키북스',
    originalPrice: 45000,
    salePrice: 40500,
    discountRate: 10,
    pointReward: 2250,
    category: 'IT/개발 베스트',
    coverColor: '#0F172A', // Slate Dark
    coverLabel: '모던\n자바스크립트\nDeep Dive',
    supportType: 'general',
    supportBadge: '개발자 필독서 무료배송',
    shippingInfo: '무료배송',
    estimatedSelfPay: 40500,
    benefitDiscount: 0,
    wishDate: '2026.09.05',
    selected: true,
    likesCount: 3120,
  },
  {
    id: 'b-5',
    title: '『마흔에 읽는 쇼펜하우어』',
    subTitle: '마음의 위기를 다스리는 철학의 수업',
    author: '강용수',
    publisher: '유노서가',
    originalPrice: 17000,
    salePrice: 15300,
    discountRate: 10,
    pointReward: 850,
    category: '인문철학',
    coverColor: '#7C2D12', // Warm Deep Rust
    coverLabel: '마흔에 읽는\n쇼펜하우어',
    supportType: 'general',
    supportBadge: '임직원 도서 지원 대상',
    shippingInfo: '오늘출발 (17시 이전 결제)',
    estimatedSelfPay: 15300,
    benefitDiscount: 0,
    wishDate: '2026.08.28',
    selected: true,
    likesCount: 8940,
  },
];

export const initialCartBooks: BookItem[] = [
  {
    id: 'cart-1',
    title: '『AI 시대의 일하는 방식』',
    author: '김영훈',
    publisher: '위즈덤하우스',
    originalPrice: 18000,
    salePrice: 16200,
    discountRate: 10,
    pointReward: 900,
    category: '추천도서',
    coverColor: '#1E3A8A',
    coverLabel: 'AI 시대의\n일하는 방식',
    supportType: 'recommended',
    supportBadge: '100% 지원대상',
    shippingInfo: '내일(수) 도착 예정 (무료배송)',
    quantity: 1,
    selected: true,
  },
  {
    id: 'cart-2',
    title: '『트렌드 코리아 2026』',
    author: '김난도 외',
    publisher: '미래의창',
    originalPrice: 20000,
    salePrice: 18000,
    discountRate: 10,
    pointReward: 1000,
    category: '개인도서',
    coverColor: '#DC2626',
    coverLabel: '트렌드\n코리아 2026',
    supportType: 'personal',
    supportBadge: '지원금 50% 적용가능',
    shippingInfo: '내일(수) 도착 예정 (무료배송)',
    quantity: 1,
    selected: true,
  },
  {
    id: 'cart-3',
    title: '『모던 자바스크립트 Deep Dive』',
    author: '이웅모',
    publisher: '위키북스',
    originalPrice: 45000,
    salePrice: 40500,
    discountRate: 10,
    pointReward: 2250,
    category: '일반/전문도서',
    coverColor: '#0F172A',
    coverLabel: '전문도서\n모던 JS\nDeep Dive',
    supportType: 'general',
    supportBadge: '개인도서 지원 가능',
    shippingInfo: '모레(목) 도착 예정 (무료배송)',
    quantity: 1,
    selected: true,
  },
];

export const initialOrders: OrderItem[] = [
  {
    orderNumber: 'YP20260914-8841',
    orderDate: '2026.09.14',
    status: '상품준비중',
    statusDescription: '내일(화) 도착 예정',
    paymentMethod: '신용카드(현대카드)',
    shippingAddress: '서울특별시 강남구 강남대로 408 YBM빌딩 지하 1층 영풍문고 강남점',
    totalPrice: 34200,
    totalBenefitAmount: 21200,
    finalPaidAmount: 13000,
    items: [
      {
        bookId: 'ord-b1',
        title: '『AI 시대의 일하는 방식』',
        author: '김영훈',
        publisher: '위즈덤하우스',
        quantity: 1,
        category: '추천도서',
        coverColor: '#1E3A8A',
        coverLabel: 'AI 시대의\n일하는 방식',
        originalPrice: 18000,
        salePrice: 16200,
        supportType: 'recommended',
        supportLabel: '추천도서 100% 임직원 지원',
        benefitAmount: 16200,
        selfPay: 0,
        status: '상품준비중',
      },
      {
        bookId: 'ord-b2',
        title: '『트렌드 코리아 2026』',
        author: '김난도 외',
        publisher: '미래의창',
        quantity: 1,
        category: '개인도서',
        coverColor: '#DC2626',
        coverLabel: '트렌드\n코리아\n2026',
        originalPrice: 20000,
        salePrice: 18000,
        supportType: 'personal',
        supportLabel: '개인도서 지원금 5,000원 적용',
        benefitAmount: 5000,
        selfPay: 13000,
        status: '결제완료',
      },
    ],
  },
  {
    orderNumber: 'YP20260904-0193',
    orderDate: '2026.09.04',
    status: '배송완료',
    statusDescription: '배송 완료',
    deliveryTracker: {
      carrier: 'CJ대한통운',
      trackingNumber: '6849-2910-4491',
    },
    paymentMethod: '카카오페이',
    shippingAddress: '서울특별시 강남구 강남대로 408 YBM빌딩 지하 1층 영풍문고 강남점',
    totalPrice: 24000,
    totalBenefitAmount: 5000,
    finalPaidAmount: 19000,
    items: [
      {
        bookId: 'ord-b3',
        title: '『프로덕트 매니지먼트의 모든 것』',
        author: '맷 르메이',
        publisher: '인사이트',
        quantity: 1,
        category: '경제/경영',
        coverColor: '#1E293B',
        coverLabel: '경제/경영\n프로덕트\n매니지먼트',
        originalPrice: 24000,
        salePrice: 24000,
        supportType: 'personal',
        supportLabel: '개인도서 지원 5,000원 적용',
        benefitAmount: 5000,
        selfPay: 19000,
        status: '배송완료',
      },
    ],
  },
];

export const refundHistories: RefundHistoryItem[] = [
  {
    id: 'rf-1',
    receiptNumber: 'RF20260820-0041',
    date: '2026.08.20',
    type: '반품환불',
    bookTitle: '『마흔에 읽는 쇼펜하우어』',
    authorAndPublisher: '유노서가 | 1권 (주문번호: YP20260815-9920)',
    orderNumber: 'YP20260815-9920',
    reason: '단순 변심 (미개봉 도서 회수)',
    refundAmount: 12800,
    benefitRestored: '배송비 -2,500원 차감 / 적립금 850P 회수 완료',
    status: '환불완료',
    processedDate: '2026.08.23 처리',
  },
  {
    id: 'rf-2',
    receiptNumber: 'RF20260712-0118',
    date: '2026.07.12',
    type: '주문취소',
    bookTitle: '『AI 시대의 일하는 방식』',
    authorAndPublisher: '위즈덤하우스 | 1권 (출고 전 취소)',
    orderNumber: 'YP20260710-4412',
    reason: '출고 전 주문 취소 (배송 전 즉시 취소)',
    refundAmount: 16200,
    benefitRestored: '추천도서 100% 한도 복구 / 전액 승인취소',
    status: '취소완료',
    processedDate: '2026.07.12 처리',
  },
];

export const recommendedBook100List = [
  { id: 'rec-1', title: '『AI 시대의 일하는 방식』', author: '김영훈', publisher: '위즈덤하우스', category: '자기계발/IT', price: 18000 },
  { id: 'rec-2', title: '『생각에 관한 생각』', author: '대니얼 카너먼', publisher: '김영사', category: '인문/심리', price: 22000 },
  { id: 'rec-3', title: '『클린 코드 (Clean Code)』', author: '로버트 C. 마틴', publisher: '인사이트', category: 'IT/개발', price: 33000 },
  { id: 'rec-4', title: '『린 스타트업』', author: '에릭 리스', publisher: '비즈니스북스', category: '경영/전략', price: 19800 },
  { id: 'rec-5', title: '『초격차 : 리더의 질문』', author: '권오현', publisher: '쌤앤파커스', category: '리더십', price: 18000 },
  { id: 'rec-6', title: '『사피엔스』', author: '유발 하라리', publisher: '김영사', category: '역사/인문', price: 24000 },
  { id: 'rec-7', title: '『원칙 (Principles)』', author: '레이 달리오', publisher: '한빛비즈', category: '투자/경영', price: 35000 },
  { id: 'rec-8', title: '『데일 카네기 인간관계론』', author: '데일 카네기', publisher: '현대지성', category: '자기계발', price: 11500 },
];
